# FT-IR Background Monitor - plot_spectrum.py
# Version: 1.5
# Roberto Moscetti - University of Tuscia, Italy
# Contact: rmoscetti@unitus.it
# License: MIT
#
# Script used in the OMNIC workflow.
# The TSV exported by OMNIC is copied to background_stability.tsv.
# The previous spectrum is kept in background_stability_old.tsv.
# The script compares the current background with the previous one and with reference.tsv.
# The plot is written to plot_background.png as a four-panel figure.
# RMS and max absolute log-ratio values are also saved in plot_background_metrics.txt.

from pathlib import Path
import csv
import os
import shutil
import sys
from datetime import datetime

# Used to load the packages from the .deps folder
sys.path.insert(0, str(Path(__file__).resolve().with_name(".deps")))

import numpy as np  # type: ignore[import-not-found]
import matplotlib  # type: ignore[import-not-found]

matplotlib.use("Agg")  # Avoids opening a plot window
import matplotlib.pyplot as plt  # type: ignore[import-not-found]

base = Path(__file__).resolve().parent
reference_tsv = base / "reference.tsv"
current_tsv = base / "background_stability.tsv"
old_tsv = base / "background_stability_old.tsv"
png = base / "plot_background.png"
txt = base / "plot_background_metrics.txt"
tmp = (base / "plot_background.tmp.png")  # Temporary file used to avoid read/write issues with view_plot.py
old = True

omnic_tsv = list(base.glob("*BG_snapshot*TSV"))  # Looks for the TSV file generated by OMNIC Paradigm
shutil.copyfile(omnic_tsv[0], current_tsv)  # Copies the OMNIC TSV to a simpler file name
if not old_tsv.exists():  # Avoids a missing old file on the first cycle
    shutil.copyfile(current_tsv, old_tsv)
    old = False

# Creates the vectors used for the plot
old_x, old_y, new_x, new_y, ref_x, ref_y = [], [], [], [], [], []

# Fills the vectors with the TSV data
for path, x, y in ((old_tsv, old_x, old_y), (current_tsv, new_x, new_y), (reference_tsv, ref_x, ref_y)):
    with path.open(newline="") as f:
        rows = csv.reader(f, delimiter="\t")
        next(rows, None)  # Ignores the first TSV line
        for row in rows:
            x.append(float(row[0].replace(",", ".")))
            y.append(float(row[1].replace(",", ".")))

# Converts the lists to numpy arrays
old_x = np.array(old_x)
old_y = np.array(old_y)
new_x = np.array(new_x)
new_y = np.array(new_y)
ref_x = np.array(ref_x)
ref_y = np.array(ref_y)

# Masks used to keep CH and fingerprint regions
mask_ch = (new_x >= 2700) & (new_x <= 3200)
mask_fingerprint = (new_x >= 600) & (new_x <= 1200)

# Region of interest for CH and fingerprint regions
roi = mask_ch | mask_fingerprint
new_x_roi = new_x[roi]
new_y_roi = new_y[roi]
old_x_roi = old_x[roi]
old_y_roi = old_y[roi]
ref_x_roi = ref_x[roi]
ref_y_roi = ref_y[roi]

# Converts raw data to background log-ratio and computes RMS
# new vs old
bg_log_ratio = -np.log10(new_y_roi / old_y_roi)  # Log-ratio -log10(I/Io)
rms1 = np.round(np.sqrt(np.mean(bg_log_ratio**2)), 4)  # Root Mean Square
max_abs_bg_log_ratio = np.round(np.max(np.abs(bg_log_ratio)), 4)  # Maximum absolute log-ratio value
# new vs reference
ref_log_ratio = -np.log10(new_y_roi / ref_y_roi)  # Log-ratio -log10(I/Io)
rms2 = np.round(np.sqrt(np.mean(ref_log_ratio**2)), 4)  # Root Mean Square
max_abs_ref_log_ratio = np.round(np.max(np.abs(ref_log_ratio)), 4)  # Maximum absolute log-ratio value

timestamp = datetime.now().strftime("%d/%m/%Y %H:%M:%S")

# Saves RMS and max absolute log-ratio in a txt file
with txt.open("a") as f:
    f.write(f"{timestamp}\tRMS1={rms1}\tRMS2={rms2}\tMAX_ABS_BG_LOG_RATIO={max_abs_bg_log_ratio}\tMAX_ABS_REF_LOG_RATIO={max_abs_ref_log_ratio}\n")

# Draws the plot
fig, axes = plt.subplots(2, 2, figsize=(16, 16))
axes = axes.ravel()

# Highlights the ROI in both subplots
for ax in axes:
    ax.axvspan(2700, 3200, color="gold", alpha=0.35)
    ax.axvspan(600, 1200, color="gold", alpha=0.35)

if old:
    axes[0].plot(old_x, old_y, color="red", linewidth=0.8, label="Old")
axes[0].plot(new_x, new_y, color="blue", linewidth=0.8, label="New")
axes[0].grid(True, color="lightgray")
axes[0].set_xlim(max(max(old_x), max(new_x)), min(min(old_x), min(new_x)))
axes[0].set_title("Raw spectra")
axes[0].set_xlabel("Wavenumber (cm^-1)")
axes[0].set_ylabel("Intensity")
if old:
    axes[0].legend()

axes[1].axhline(0, color="black", linewidth=1, linestyle="--")
axes[1].plot(new_x_roi, bg_log_ratio, color="green", linewidth=0.8, label="Background log-ratio")
axes[1].grid(True, color="lightgray")
axes[1].set_xlim(max(max(old_x), max(new_x)), min(min(old_x), min(new_x)))
axes[1].set_title(f"Background log-ratio | RMS1: {rms1} | Max abs: {max_abs_bg_log_ratio}")
axes[1].set_xlabel("Wavenumber (cm^-1)")
axes[1].set_ylabel("Background log-ratio")

axes[2].plot(ref_x, ref_y, color="purple", linewidth=0.8, label="Reference")
axes[2].plot(new_x, new_y, color="blue", linewidth=0.8, label="New")
axes[2].grid(True, color="lightgray")
axes[2].set_xlim(max(max(ref_x), max(new_x)), min(min(ref_x), min(new_x)))
axes[2].set_title("Reference vs New")
axes[2].set_xlabel("Wavenumber (cm^-1)")
axes[2].set_ylabel("Intensity")
axes[2].legend()

axes[3].axhline(0, color="black", linewidth=1, linestyle="--")
axes[3].plot(new_x_roi, ref_log_ratio, color="green", linewidth=0.8, label="Background log-ratio")
axes[3].grid(True, color="lightgray")
axes[3].set_xlim(max(max(ref_x), max(new_x)), min(min(ref_x), min(new_x)))
axes[3].set_title(f"Background log-ratio | RMS2: {rms2} | Max abs: {max_abs_ref_log_ratio}")
axes[3].set_xlabel("Wavenumber (cm^-1)")
axes[3].set_ylabel("Background log-ratio")

fig.suptitle(timestamp)
fig.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig(tmp, dpi=58)  # Saves the plot first to the temporary file
plt.close()
os.replace(tmp, png)  # Replaces the final PNG with the temporary one
os.replace(current_tsv, old_tsv)  # Moves current TSV to old TSV for the next cycle
