# FT-IR Background Monitor - plot_spectrum.py
# Version: 1.2.0
# Roberto Moscetti - University of Tuscia, Italy
# Contact: rmoscetti@unitus.it
# License: MIT
#
# Script used in the OMNIC workflow.
# The TSV exported by OMNIC is copied to background_stability.tsv.
# The previous spectrum is kept in background_stability_old.TSV.
# The script then updates current_background.png.
# Old spectrum in red, current spectrum in blue.

from pathlib import Path
import csv
import os
import shutil
import sys
from datetime import datetime

# Used to load the packages from the .deps folder
sys.path.insert(0, str(Path(__file__).resolve().with_name(".deps")))

import matplotlib  # type: ignore[import-not-found]

matplotlib.use("Agg")  # Avoids opening a plot window
import matplotlib.pyplot as plt  # type: ignore[import-not-found]

base = Path(__file__).resolve().parent
current_tsv = base / "background_stability.tsv"
old_tsv = base / "background_stability_old.tsv"
png = base / "plot_background.png"
tmp = (base / "plot_background.tmp.png")  # Temporary file used to avoid read/write issues with view_plot.py
old = True

omnic_tsv = list(base.glob("*BG_snapshot*TSV"))  # Looks for the TSV file generated by OMNIC Paradigm
shutil.copyfile(omnic_tsv[0], current_tsv)  # Copies the OMNIC TSV to a simpler file name
if not old_tsv.exists():  # Avoids a missing old file on the first cycle
    shutil.copyfile(current_tsv, old_tsv)
    old = False

# Creates the vectors used for the plot
old_x = []
old_y = []
new_x = []
new_y = []

# Fills the vectors with the TSV data
for path, x, y in ((old_tsv, old_x, old_y), (current_tsv, new_x, new_y)):
    with path.open(newline="") as f:
        rows = csv.reader(f, delimiter="\t")
        next(rows, None)  # Ignores the first TSV line
        for row in rows:
            x.append(float(row[0].replace(",", ".")))
            y.append(float(row[1].replace(",", ".")))

# Draws the plot
plt.figure(figsize=(11, 7))
if old:
    plt.plot(old_x, old_y, color="red", linewidth=0.8, label="Old")
plt.plot(new_x, new_y, color="blue", linewidth=0.8, label="New")
plt.grid(True, color="lightgray")
plt.xlim(max(max(old_x), max(new_x)), min(min(old_x), min(new_x)))
plt.title(datetime.now().strftime("%d/%m/%Y %H:%M:%S"))
if old:
    plt.legend()
plt.tight_layout()
plt.savefig(tmp, dpi=100)  # Saves the plot first to the temporary file
plt.close()
os.replace(tmp, png)  # Replaces the final PNG with the temporary one
os.replace(current_tsv, old_tsv)  # Moves current TSV to old TSV for the next cycle
