# FT-IR Background Monitor - plot_spectrum.py
# Version: 1.3.0
# Roberto Moscetti - University of Tuscia, Italy
# Contact: rmoscetti@unitus.it
# License: MIT
#
# Script used in the OMNIC workflow.
# The TSV exported by OMNIC is copied to background_stability.tsv.
# The previous spectrum is kept in background_stability_old.tsv.
# The script then updates plot_background.png.
# Raw spectra and background log-ratio are shown side by side.

from pathlib import Path
import csv
import os
import shutil
import sys
from datetime import datetime

# Used to load the packages from the .deps folder
sys.path.insert(0, str(Path(__file__).resolve().with_name(".deps")))

import numpy as np  # type: ignore[import-not-found]
import matplotlib  # type: ignore[import-not-found]

matplotlib.use("Agg")  # Avoids opening a plot window
import matplotlib.pyplot as plt  # type: ignore[import-not-found]

base = Path(__file__).resolve().parent
current_tsv = base / "background_stability.tsv"
old_tsv = base / "background_stability_old.tsv"
png = base / "plot_background.png"
tmp = (
    base / "plot_background.tmp.png"
)  # Temporary file used to avoid read/write issues with view_plot.py
old = True

omnic_tsv = list(
    base.glob("*BG_snapshot*TSV")
)  # Looks for the TSV file generated by OMNIC Paradigm
shutil.copyfile(
    omnic_tsv[0], current_tsv
)  # Copies the OMNIC TSV to a simpler file name
if not old_tsv.exists():  # Avoids a missing old file on the first cycle
    shutil.copyfile(current_tsv, old_tsv)
    old = False

# Creates the vectors used for the plot
old_x, old_y, new_x, new_y = [], [], [], []

# Fills the vectors with the TSV data
for path, x, y in ((old_tsv, old_x, old_y), (current_tsv, new_x, new_y)):
    with path.open(newline="") as f:
        rows = csv.reader(f, delimiter="\t")
        next(rows, None)  # Ignores the first TSV line
        for row in rows:
            x.append(float(row[0].replace(",", ".")))
            y.append(float(row[1].replace(",", ".")))

# Converts the lists to numpy arrays
old_x = np.array(old_x)
old_y = np.array(old_y)
new_x = np.array(new_x)
new_y = np.array(new_y)

# Masks used to keep CH and fingerprint regions
mask_ch = (new_x >= 2700) & (new_x <= 3200)
mask_fingerprint = (new_x >= 600) & (new_x <= 1200)

# Region of interest for CH and fingerprint regions
roi = mask_ch | mask_fingerprint
new_x_roi = new_x[roi]
new_y_roi = new_y[roi]
old_x_roi = old_x[roi]
old_y_roi = old_y[roi]

# Converts raw data to background log-ratio and computes RMS
bg_log_ratio = -np.log10(new_y_roi / old_y_roi)  # Log-ratio -log10(I/Io)
rms = np.round(np.sqrt(np.mean(bg_log_ratio**2)), 4)  # Root Mean Square

# Draws the plot
fig, axes = plt.subplots(1, 2, figsize=(16, 7))

if old:
    axes[0].plot(old_x, old_y, color="red", linewidth=0.8, label="Old")
axes[0].plot(new_x, new_y, color="blue", linewidth=0.8, label="New")
axes[0].grid(True, color="lightgray")
axes[0].set_xlim(max(max(old_x), max(new_x)), min(min(old_x), min(new_x)))
axes[0].set_title("Raw spectra")
if old:
    axes[0].legend()

axes[1].axhline(
    0, color="black", linewidth=1, linestyle="--"
)  # Zero line used as reference
axes[1].plot(
    new_x_roi,
    bg_log_ratio,
    color="green",
    linewidth=0.8,
    label="Background log-ratio",
)
axes[1].grid(True, color="lightgray")
axes[1].set_xlim(max(max(old_x), max(new_x)), min(min(old_x), min(new_x)))
axes[1].set_title(f"Background log-ratio | RMS: {rms}")


fig.suptitle(datetime.now().strftime("%d/%m/%Y %H:%M:%S"))
fig.tight_layout()
plt.savefig(tmp, dpi=100)  # Saves the plot first to the temporary file
plt.close()
os.replace(tmp, png)  # Replaces the final PNG with the temporary one
os.replace(current_tsv, old_tsv)  # Moves current TSV to old TSV for the next cycle
